spring:
  application:
    name: api-service

  data:
    mongodb:
      auto-index-creation: false
      uri: ${MONGO_DATABASE_URI}
      database: ${MONGO_DATABASE_NAME}
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4.1
          temperature: 0.7
          max-tokens: 2000
          top-p: 1.0
